### PR TITLE
Add memoization for faster array conversions

### PR DESCRIPTION
**Pull request by lynxtaa**
Creating memoization cache before converting an array of objects significantly improves performance (6-7 times faster). 

Measured with 2000 objects (every object had same set of 100 keys):
before -- 260ms 
after -- 40ms

### CODE REVIEW

**Comment by Kequc** [comment]
Good idea. Let me take a look at this implementation when I have some time, perhaps when I get back from vacation. I didn't realise stringcase was slow. :+1:

**Comment by lynxtaa** [comment]
Thanks! Stringcase is slow and, as a result, performance is degrading linearly when number of rows increases. We'll benefit from the fact that every row has the same set of keys

**Comment by Kequc** [comment]
What do you think if there was a cache of all uses of the `convert` function, and it persisted throughout the application's life? If you had something like even 1000 keys stored there do you think that would be an inappropriate use of memory?

It's probably minimal.

If you've got that much data you're probably accessing the database quite often. So the thought, and maybe I'm wrong, is to keep the converted keys.

**Comment by lynxtaa** [comment]
Yeah, this approach will improve performance even more. 

There are some scenarios when database schema is changing constantly without restarting the application -- as a result memoization cache will grow constantly in memory. But I think it's quite improbable. 

I'll try to implement proposed solution

**Comment by Kequc** [comment]
Scenarios where database schema is changing? During runtime? That's crazy though I suppose possible, is it common? What are the use cases for such things.

**Comment by lynxtaa** [comment]
Like I said it's quite improbable scenarios, we can ignore them :)

**Comment by Kequc** [comment]
Not to step on your toes however I've created a new pull request with the caching done inside of the get-converters methods rather than index. I was hoping you could take a look let me know if I'm missing anything from the implementation.

Tell me which pr I should merge!

https://github.com/Kequc/knex-stringcase/pull/11

**Comment by lynxtaa** [comment]
LGTM, closing this one

**Comment by Kequc** [comment]
ty ty

**Pull request closed without merging**
