### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by felixmosh**
This PR adds basic types that allows autocomplete of Knex options when using this lib :]

image

### CODE REVIEW

**Comment by Kequc** [comment]
Putting aside that I'm not sure I want to add types to a configuration lib. Also putting aside that this implementation imports knex which is not a dependency of the package and will cause linters to complain. The implementation itself seems to be incorrect, `wrapIdentifier` is a method exposed by knex, not my library. There are several other variables which are exposed by this library that are not included here.

Do we really need a type file for something that will be setup one time and never looked at again? The overhead of maintaining types doesn't seem worth it at all.

**Comment by felixmosh** [comment]
I had a typo in this config for a long time, If I had those types it was prevented in a second.

The  fact is that Knex providing those types and you don't have any overhead of maintaining them.

> The implementation itself seems to be incorrect, wrapIdentifier is a method exposed by knex, not my library. There are several other variables which are exposed by this library that are not included here.
This is the type of the object that your lib accepts, the Knex Config Object.

If you think about it, your lib should have Knex as a peer deps anyway.

**Comment by Kequc** [comment]
> If you think about it, your lib should have Knex as a peer deps anyway.

That's only true if I use your type file because otherwise the knex lib isn't imported anywhere in this repository. Then because it's a dependency the library would need to be updated to coincide with updates to knex, and it would be a problem for everyone trying to use this library because they might be ending up with a version of knex they don't want.

That's an example of where additional maintenance is introduced.

**Comment by Kequc** [comment]
If you want to use types with this library which only really adds two config options. I recommend merging the options returned from this library separately.

```knexStringcase();```

The above gives you an object with only `wrapIdentifier` and `postProcessResponse`, you can assign them directly over top of your configuration.

```Object.assign(myOptions, knexStringcase());```

Like so.

**Comment by felixmosh** [comment]
I don't think that this approach is what needed. Anyway, since you not approve it there are much better workaround, such as casting.

**Pull request closed without merging**
